backend:
  name: git-gateway
  branch: master
media_folder: "content/images"
collections:
  - name: "schedule"
  - label: "Horarios"
  - folder: "content/schedule"
  - create: false
  - slug: "{{slug}}"